site_name: orom's knowledge base
theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/icon.svg

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.path


  # disables loading fonts from Google Fonts
  font: false

  palette:
    # dark mode
    - scheme: default
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
      primary: black
      accent: blue grey

    # light mode
    - scheme: slate
      toggle:
        icon: octicons/moon-16
        name: Switch to light mode
      #primary: black
      #accent: black

nav:
  - "index.md"
  - "get-started.md"
  - "about.md"
  - "contribute.md"
  - "Main Website": "https://www.openroboticmetaverse.org"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  consent:
    title: Cookie consent
    actions:
      - accept
      - reject
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/openroboticmetaverse
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/openroboticmetaverse
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/openroboticmetaverse
    - icon: fontawesome/brands/edge
      link: https://www.openroboticmetaverse.org
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/orom_org
  analytics:
    provider: google
    property: G-N1TE3R198F
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thank you for your feedback! Help us improve this page by <a href="https://openroboticmetaverse.org/contact" target="_blank" rel="noopener">contacting us</a>.

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2023 <a href="https://www.openroboticmetaverse.org"  target="_blank" rel="noopener">open robotic metaverse</a> - 
  <a href="#__consent">Change cookie settings</a>


repo_url: https://github.com/openroboticmetaverse/knowledge-base
repo_name: openroboticmetaverse
edit_uri: edit/main/docs/
