site_name: Open Roboverse Knowledge Base
theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/icon.svg

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.path


  # disables loading fonts from Google Fonts
  font: false

  palette:
    # dark mode
    - scheme: default
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
      primary: black
      accent: blue grey

    # light mode
    - scheme: slate
      toggle:
        icon: octicons/moon-16
        name: Switch to light mode
      #primary: black
      #accent: black

nav:
  - "index.md"
  - "get-started.md"
  - "about.md"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  consent:
    title: Cookie consent
    actions:
      - accept
      - reject
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/openroboverse
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/openroboverse
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/openroboverse

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2023 <a href="https://github.com/openroboverse"  target="_blank" rel="noopener">Open Roboverse</a> - 
  <a href="#__consent">Change cookie settings</a>

repo_url: https://github.com/openroboverse/knowledge-base
repo_name: openroboverse/knowledge-base
edit_uri: edit/main/docs/
